import { BASE_HEIGHT, EARTH_BODY_DIAMETER } from "./coords";

export const TAP_NEUTRAL_THRESHOLD_PX = 18;
export const MISS_COMMIT_DISTANCE_PX = 42;
export const LIVE_SEGMENT_MIN_LENGTH_PX = 12;

export const NORMAL_SLASH_HIT_INFLATE_PX = 12;
export const SOLAR_LANCE_HIT_INFLATE_PX = EARTH_BODY_DIAMETER;
export const SOLAR_LANCE_VFX_WIDTH_PX = EARTH_BODY_DIAMETER * 2;
export const SAME_STROKE_REHIT_EXIT_MARGIN_PX = 12;
export const SAME_STROKE_REHIT_COOLDOWN_MS = 80;
export const ENEMY_HIT_SHAKE_DURATION_MS = 180;
export const ENEMY_HIT_SHAKE_INTENSITY_PX = 24;

export const STROKE_TRAIL_MAX_LENGTH_PX = BASE_HEIGHT * 1.4;
export const STROKE_BUFFER_HARD_CAP_PX = BASE_HEIGHT * 1.5;
